[package]
name = "rupdateproxy"
version = "0.1.0"
authors = ["Tom Pusateri <pusateri@bangj.com>"]
homepage = "https://github.com/pusateri/rupdateproxy"

[dependencies]
tokio = "0.1"
tokio-codec = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.2"
futures = "0.1"
lazy_static = "^1.0"
socket2 = { version = "0.3.7", features = ["reuseport"] }
bytes = "*"
domain-core = "*"
nix = "*"
hostname ="*"
treebitmap = { git = "https://github.com/zesplot/treebitmap.git", branch = "longest_match_mut" }
ipnetwork = "*"
jsonpath = "*"
json-patch = "*"
shrust = "*"
argparse = "0.2.2"
daemonize = "0.3.0"

[build-dependencies]
git-version = "*"
