[package]
name = "rupdateproxy"
version = "0.1.0"
authors = ["Tom Pusateri <pusateri@bangj.com>"]

[dependencies]
tokio = "0.1"
tokio-codec = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.2"
futures = "0.1"
lazy_static = "^1.0"
socket2 = { version = "0.3.7", features = ["reuseport"] }
bytes = "*"
domain-core = "*"
